// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2OjC-L9htStnnneOUPA-Eld7XLl9fq-c',
    appId: '1:852777786427:web:3f5e761a2c5589aa77901e',
    messagingSenderId: '852777786427',
    projectId: 'mcg-app-998e9',
    authDomain: 'mcg-app-998e9.firebaseapp.com',
    storageBucket: 'mcg-app-998e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYYgprAD9vKA5MPPVTdVJQsVgYyGEWass',
    appId: '1:852777786427:android:0f0d5e131c28a23477901e',
    messagingSenderId: '852777786427',
    projectId: 'mcg-app-998e9',
    storageBucket: 'mcg-app-998e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtpHL8Y2yIPKjCJxIMgvxCcEvDSMQKn2E',
    appId: '1:852777786427:ios:517ae8aafbba4d8a77901e',
    messagingSenderId: '852777786427',
    projectId: 'mcg-app-998e9',
    storageBucket: 'mcg-app-998e9.appspot.com',
    iosClientId: '852777786427-o9vh4nmo9gv1a6hnl6ddin466088erqr.apps.googleusercontent.com',
    iosBundleId: 'xyz.hafemann.mcgapp.mcgapp',
  );
}
